name: Deploy to WordPress.org
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to WordPress.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get plugin version
        id: plugin_version
        run: |
          VERSION=$(grep -m 1 "Version:" media-restriction.php | awk -F': ' '{print $2}' | tr -d '\r')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: media-restriction
          VERSION: ${{ steps.plugin_version.outputs.version }}
        with:
          generate-zip: true